## SPDX-License-Identifier: GPL-2.0-only

meta_version		= 1.7.7
meta_protocol		= org.uefi.capsule
meta_type		= X-System
meta_format		= pair
meta_no_ux_capsule	= 0
meta_device_flags	= $(if $(filter 1 true yes,$(meta_no_ux_capsule)),no-ux-capsule,)
meta_branch		= true
meta_guid_1		= $(coreboot_caps)
file_type		= cap
