## SPDX-License-Identifier: GPL-2.0-only

ifeq ($(target),ite)
meta_version		= 1.7.0
meta_protocol		= tw.com.ite.superio
meta_type		= X-EmbeddedController
meta_format		= pair
meta_branch		= false
meta_guid_1		= $(superio1)
meta_guid_2		= $(superio2)
file_type		= bin

nsh_tool		= $(ite_tool)
nsh_selector		= $(ite_selector)
nsh_switch		= $(ite_switch)

else ifeq ($(target),coreboot)
meta_version		= 1.7.7
meta_protocol		= org.flashrom
meta_type		= X-System
meta_format		= pair
meta_branch		= true
meta_guid_1		= $(coreboot)
meta_guid_2		= $(ami)
file_type		= rom

else ifeq ($(target),ami)
meta_version		= 1.3.9
meta_protocol		= org.uefi.capsule
meta_type		= X-System
meta_format		= triplet
meta_branch		= false
meta_guid_1		= $(uefi)
file_type		= cap

nsh_tool		= AfuEfix64
nsh_switch		= $(ami_switch)

else ifeq ($(target),ami-flashrom)
meta_version		= 1.7.7
meta_protocol		= org.flashrom
meta_type		= X-System
meta_format		= triplet
meta_branch		= false
meta_guid_1		= $(coreboot)
file_type		= bin

endif

