## SPDX-License-Identifier: GPL-2.0-only

ifeq ($(model),lite_apl)
name		= StarLite MkII
sku		= I2
hwid		= 80f1fd54-f581-571f-90e6-00bf8a67f627
coreboot_caps	= 5d9d096d-2c62-4bfd-b2ed-a5ce77dcc9e6

else ifeq ($(model),lite_glk)
name		= StarLite MkIII
sku		= I3
hwid		= d5521faa-c50b-5d64-971d-8fd400030c51
coreboot_caps	= 5070631a-0521-4177-bb78-1672c6716a03

else ifeq ($(model),lite_glkr)
name		= StarLite MkIV
sku		= I4

hwid		= 0fc25c8c-ffa8-54ad-a216-d13cfe75bee4
coreboot_caps	= a0382981-b0e3-4ae5-98c4-cbf6c7a16860

else ifeq ($(model),labtop_kbl)
name		= LabTop MkIII
sku		= L3

hwid		= 61329016-2c61-5873-8682-ab300694452e
coreboot_caps	= 9f84eb61-f9c5-489a-baf4-c9ad13d72060

else ifeq ($(model),labtop_cml)
name		= LabTop MkIV
sku		= L4
hwid		= baf1d04e-fd16-5e6a-93cc-1c23d171f879
coreboot_caps	= d33fbe7d-90b9-493e-9a94-2a63dc915044

else ifeq ($(model),starbook_tgl)
name		= StarBook MkV
sku		= B5

hwid		= 85aba599-addd-5985-a2e8-eddb41c61ba3
coreboot_caps	= 78681eee-2edc-4575-a861-d593f8145ce0

else ifeq ($(model),starbook_adl)
name		= StarBook MkVI-Intel
sku		= B6-I
hwid		= 5c917039-d938-5c9a-b22a-9c392b1534f3
coreboot_caps	= d86dddc7-8e8e-45b8-a830-d5d602467bcc

else ifeq ($(model),starbook_cezanne)
name		= StarBook MkVI-AMD
sku		= B6-A
hwid		= b39593ad-7522-52a5-a4ab-1b2ca2153956
coreboot_caps	= 2ef5db2f-2791-4e62-bd7b-fdb23f83c615

else ifeq ($(model),byte_cezanne)
name		= Byte MkI
sku		= Y1

hwid		= 79a64046-5643-59c4-91d0-e68b33db5829
coreboot_caps	= 83335bd5-ec9e-4a78-8931-223d990f5b44

else ifeq ($(model),starbook_rpl)
name		= StarBook MkVIr2-Intel
sku		= B62-I
hwid		= 12122d1c-c383-5583-9cb7-3ba8d220913d
coreboot_caps	= 6d5381ba-53ea-426e-bf5d-a9c722b1f45f

else ifeq ($(model),byte_adl)
name		= Byte MkII
sku		= Y2
hwid		= ef9b469e-2429-53e6-b4c0-3646ac0f53ed
coreboot_caps	= 1bb1161f-9939-4213-8744-32887dd9514f
meta_branch	= false

else ifeq ($(model),lite_adl)
name		= StarLite MkV
sku		= I5
hwid		= 3d9415bb-3027-541b-99b7-cf21e5383bdb
coreboot_caps	= 975cd0e6-c540-4e2b-906c-72c0d0d1e40d
meta_branch	= false

else ifeq ($(model),starfighter_rpl)
name		= StarFighter MkI
sku		= F1
hwid		= 9299159f-8ac4-5e25-81f3-e8cf2ae62f32
coreboot_caps	= ac75492e-18ad-477d-a719-710a0ddb6c2c
meta_branch	= false

else ifeq ($(model),starbook_adl_n)
name		= StarBook MkVII-N
sku		= B7-N
hwid		= a03a57fd-a71b-5166-a2f2-5eef4ad5c22d
coreboot_caps	= 231fcee3-2374-416d-8218-088c90199a77
meta_branch	= false

else ifeq ($(model),starbook_mtl)
name		= StarBook MkVII-U
sku		= B7-U
hwid		= 3e2aba0e-9dba-52d9-a8de-2c86716459dc
coreboot_caps	= 85584837-7b03-4b6c-940c-8b6186cbf7a1
meta_branch	= false

else ifeq ($(model),byte_twl)
name		= Byte MkIII
sku		= Y3
hwid		= 49fcf7b8-0ee8-59cf-9e43-c3aa794be03b
coreboot_caps	= fb17c9c8-0cb6-43bf-9a8b-4642c61e2ac3
meta_branch	= false

else ifeq ($(model),starfighter_mtl)
name		= StarFighter MkII
sku		= F2
hwid		= daf3f999-158b-5339-917b-117d8707fee7
coreboot_caps	= 75b29ff6-e882-41c7-903f-5af89e004113
meta_branch	= false

else ifeq ($(model),adl_horizon)
name		= StarBook Horizon
sku		= HZ
hwid		= 092ff992-7ee6-5fb9-ad26-8dfabd4c84af
coreboot_caps	= 634fefb2-7099-4e5c-8b85-bd458132f51e
meta_branch	= false

endif
